### ISSUE TITLE
Problem with `markdown-in-html`

### ISSUE THREAD

**Issue by Explorare** [bordaigorl/sublime-evernote#108]
>Evernote error: [Enml validation]
	Attribute "markdown" must be declared for element type "div".
	Last command:  {}
	(Evernote plugin v2.6.0, ST 3083, Python 3.3.3, windows x64)

I met this problem when I insert a pic to note and found that only the preview to the note showed the pic but the content didn't.And the [update time] to this note didn't change after this operation.
![Image](https://hime.io/images/2015/09/02/8876658148814316.jpg)

It seems that only the attachments had been uploaded but the content didn't. But it works well when  I created a new note. Both the content and the pic were uploaded correctly.

What should I do to fix this problem?And [here](https://gist.github.com/Explorare/145c19ff892962fa9897) is one of the notes that met this problem.

And how do I delete these pic attachments if they were uploaded successfully but didn't attach to the content? 
---------------------update------------------------
I think I find a way to delete the image that uploaded successfully but failed to insert to content. Just edit the note again on EverntoeWeb or client, insert a pic, upload, then delete it. Then all the picture listed in the attachments list were deleted automaticly. But I still don't know why the content failed to update.

**Comment by bordaigorl** [comment]
The content failed to update because the `markdown2` library fails to handle the innermost `div` correctly (for some reason it treats it as a paragraph instead of raw html).
Since I am not a maintainer of the `markdown2` library, I suggest you open an issue there by isolating the problem and submitting a bug report at https://github.com/trentm/python-markdown2/issues .
While investigating this I found also this simple document

```
<div markdown="1">

<div>

</div>

</div>
```

gets wrongly translated by `markdown2` to 

```
<div>

<div>


md5-4eb9d42dbe0d156e1b0bffc28b03212a



</div>
```

Eventually I would like to ditch the buggy `markdown2` library in favour of something easier to maintain but it is a lot of work to integrate it, support existing extended syntax and test it properly.

Deleting attachments is a feature that is going to be shipped with the next version of the plugin.

**Comment by Explorare** [comment]
Thanks for your help. I'v post a issue on [Problem with `markdown-in-html` · Issue #185 · trentm/python-markdown2](https://github.com/trentm/python-markdown2/issues/185).
