### ISSUE TITLE
Markdown not working properly?

### ISSUE THREAD

**Issue by thilorichter-optimizely** [bordaigorl/sublime-evernote#126]
Update: It's not possible for me to do single line breaks either. If I insert a space between lines then I will have a space between lines as well in Evernote. If I single space lines, it's printed on the same line in Evernote. This basically means I am not able to single space anything...

This is what is in sublime text:

![screen shot 2016-03-04 at 10 09 09 am](https://cloud.githubusercontent.com/assets/16150369/13522735/994fe210-e1f1-11e5-82f6-ad94062e3d34.png)

This is what I get in Evernote:

![screen shot 2016-03-04 at 10 09 20 am](https://cloud.githubusercontent.com/assets/16150369/13522746/a67b8f02-e1f1-11e5-921b-13deb4299f55.png)

Question:

- Why do line breaks, code highlighting and lists not work properly or am I missing something? I rechecked how the markdown is supposed to look and to me everything I did looks fine. Nevertheless the output is not what is expected at all.

Thanks!

**Comment by bordaigorl** [comment]
The Markdown conversion is done by trentm/python-markdown2 not directly by the plugin.
Besides, code needs to be indented by 4 spaces and must be surrounded by empty lines. Otherwise you can use backticks `` `code` ``  for inline code or triple ones on the lines surrounding a code block

    ```
    code block
    ```

For the lists, try with empty lines to separate items.

I have plans to switch from markdown2 to some other saner converter but I have very little time to dedicate to this. Any help is appreciated :wink:

**Comment by thilorichter-optimizely** [comment]
Thanks!
