### ISSUE TITLE
html fence isn't working

### ISSUE THREAD

**Issue by mbigras** [bordaigorl/sublime-evernote#133]
I'm trying to make some notes that have html snippets of code in them using html fences; however, the fence doesn't seem to be containing the code properly:
1. in both cases "html" gets displayed in the final note
2. in the second case the html is being rendered instead of being included in a code section bound by the html code fence.
please see the attached screenshot
![html fence issue screenshot](http://cl.ly/340Q0F1y1V00/html_fence.png)

**Comment by bordaigorl** [comment]
Hi, the problem is your markdown: you need to put an empty line before and after the code fences for the parser to properly recognise the code block.
This is another annoying feature of the markdown parser that is used by the plugin, which is there mainly because that was the choice of the original author.
A mid-term goal is replacing it with a proper alternative but for now we have to live with these quirks :disappointed:
