### ISSUE TITLE
notebook name don't support non-ASCII

### ISSUE THREAD

**Issue by xyb930826** [bordaigorl/sublime-evernote#149]
notebook names lists don't support non ASCII characters.The non ASCII characters in notebook name lists will display like that:
![test](https://cloud.githubusercontent.com/assets/10846896/18815749/e48525c6-836b-11e6-8550-1dd3f1558445.png)
The characters displayed as box in the droplist is chinese characters.

**Comment by bordaigorl** [comment]
It works fine with Chinese characters for me (tested with ST3 build 3126 on MacOs).
It seems that your issue is unrelated to the plugin: looks like the font used for ST's UI does not support the Chinese character set. This can be fixed by using different themes or changing the one you are using so that the font used for the UI is one that contains Chinese symbols.
This is out of the scope of the plugin's features.

To check that this is a problem of ST and not of the plugin go to ST's console and type

    window.show_quick_panel(["筆記本"], lambda i: i)

If you see a panel displaying the chinese characters than it may be a problem of the plugin, otherwise it is an issue of ST UI's font, in which case I suggest you post a question on the [forum](https://forum.sublimetext.com/).

**Comment by xyb930826** [comment]
It seems to be the problem of sublime text UI. I'm sorry to get it wrong.
