### ISSUE TITLE
Missing blank lines when saving note to Evernote

### ISSUE THREAD

**Issue by antonio-gil** [bordaigorl/sublime-evernote#179]
Hi!

Recently I'm starting again to use ST to create and edit my Evernote notes after a 6-ish months, but I noticed something peculiar when saving my notes, and that particular thing is that the blank lines are being ignored on the client side.

So, for example, if I do a text like the following:

![2017-06-01_19h55_38](https://cloud.githubusercontent.com/assets/9835489/26707738/97558ce0-470c-11e7-83bf-a0f675582dee.png)

On the client is showed in this way:

![2017-06-01_19h56_34](https://cloud.githubusercontent.com/assets/9835489/26707787/f279357c-470c-11e7-8050-4e8de5254aa3.png)

So, the lines between the paragraphs are being ignored or removed and I don't know why. But, if I open the note back on ST, it appears to be "normal":

![2017-06-01_20h54_51](https://cloud.githubusercontent.com/assets/9835489/26707827/2bc70bf6-470d-11e7-91c2-f5d471cee4b9.png)

And that left me more clueless than before.

So, anyone has experienced or noticed this behavior before? And if so, how can it be fixed?

Thanks in advance.

Oh! And by the way these are the versions of "everyone involved":

* Sublime Text 3 Build: 3126 
* Sublime-Evernote version: 2.7.2
* Evernote Client Version: 6.6.2.5173 (305173) Prerelease
* O.S.: Windows 10 Home x64

Best regards!

**Comment by bordaigorl** [comment]
This is unfortunately due (at least as far as I can see) to undocumented inconsistencies in client-side rendering of HTML.
This is extremely frustrating: there is no guideline in how to structure the HTML to get a consistent rendering across platforms and any update in a client can potentially break it.

The generated HTML (as you can check in the console by setting the `debug` flag to `true` in the settings) wraps, as expected, the paragraphs in `<p>` elements.
Even more annoyingly, in some clients the breaklines inside paragraphs tags are not translated as word boundaries (i.e. spaces) but to nothing, resulting in the direct concatenation of adjacent lines.

I cannot reproduce the problem you mention because on Mac&WebApp paragraphs are rendered correctly.
Just to make sure there is no other problem interfering, you could check how the note is rendered in the web app by using the `Evernote: View Note in WebApp` command in ST.

**Comment by antonio-gil** [comment]
Well, I've done what you suggested, and it was the expected result:

![image](https://cloud.githubusercontent.com/assets/9835489/26748570/766bf9d4-47c4-11e7-9bd8-58c86be6431b.png)

The blank spaces are displayed correctly, and when I copy the text and paste it on the text editor, they're present.

So, I think that it's safe to assert that the client-side HTML rendering is certainly the one to blame. And the fact that there are undocumented inconsistencies doesn't help either...

Thank you for the explanation and fast response.

Regards.
