### ISSUE TITLE
note cannot add image with url

### ISSUE THREAD

**Issue by Rubbi5hThird** [bordaigorl/sublime-evernote#185]
<img src="http://img.blog.csdn.net/20150702155925873?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvc29uZ2ppbnNoaQ==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center"/>
this url can open in the browser, but can't be parsed by your plugin.......

**Comment by bordaigorl** [comment]
Hi, please be more specific, I cannot understand your issue.
What is "this url"? what does it mean to be parsed? What are you expecting the plugin to do and what is happening instead?

**Comment by Rubbi5hThird** [comment]
![img](http://img.blog.csdn.net/20150702155925873?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvc29uZ2ppbnNoaQ==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)

the plugin will issue 

Evernote complained:
The contents of the note are not valid.
The value of attribute "src" associated with an element type "img" must not contain the '<' character.
Retry?

**Comment by bordaigorl** [comment]
Thanks for the info.
The bug is caused by the markdown converter picking up the `==` in the url as "make the text in between underlined" producing a `<u></u>` pair around `/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA`.
To workaround this issue you can escape the `=` in the URLs by replacing it with `%3D` thus obtaining

```
![img](http://img.blog.csdn.net/20150702155925873?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvc29uZ2ppbnNoaQ%3D%3D/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA%3D%3D/dissolve/70/gravity/Center)
```

which should work as expected.
The markdown converter is due to be replaced with something more robust but I cannot promise any timeline.

**Comment by Rubbi5hThird** [comment]
i know it is the markdown converter, but i don't know how to solve this, thanks for your reply.
