### ISSUE TITLE
Syntax Highlighting Bug

### ISSUE THREAD

**Issue by mAAdhaTTah** [bordaigorl/sublime-evernote#80]
If you have a list, they get highlighted yellow. When you have a list [at the end of the note](https://www.evernote.com/shard/s89/sh/dd70b21c-60b6-44d6-9660-9853d8bc32ec/492ffd30c3d6a5f10197578fdfdde2f4), the links at the bottom of the document also get highlighted yellow. Should remain the current color, if possible, unless I'm doing something wrong (like indenting the links only 2 spaces instead of 4).

**Comment by bordaigorl** [comment]
Well, the highlighting is not performed by the plugin directly: the Evernote Note Syntax simply imports whichever syntax for markdown you have installed.
*This is out of the scope of the plugin.*

However I think your problem is that indeed the syntax highlighting you get is correct: if you indent paragraphs after a list item they belong to the item. I think unindenting the links completely would solve your issue.

**Comment by mAAdhaTTah** [comment]
Makes sense–I just didn't realize the Evernote Note syntax was just importing the Markdown syntax. Thanks!
